#############################################################################
# Makefile for building: ToolsLib
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sat Jul  1 21:42:39 2006
# Project:  ToolsLib.pro
# Template: app
# Command: $(QMAKE) -o Makefile ToolsLib.pro
#############################################################################

####### Compiler, tools and options

include ../Makefile.inc
#include ../Makefile.inc_static

#first: all

HEADERS = 
SOURCES =   FtpServer.cpp Constants.cpp CryptRSAGenKeys.cpp

OBJECTS =   FtpServer.o Constants.o CryptRSAGenKeys.o

TARGET  = FtpServer

all: Makefile $(TARGET)

#install

$(TARGET):  $(OBJECTS)  ../ToolsLib/ToolsLib.a ../CryptLib/CryptLib.a
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) ../ToolsLib/ToolsLib.a ../CryptLib/CryptLib.a -lfcgi

#clean:
#	-$(DEL_FILE) $(OBJECTS) $(TARGET)
#	-$(DEL_FILE) *~ core *.core

install:  
	sh -c "$(COPY_FILE) $(TARGET) $(binroot)/$(TARGET)"
	sh -c "chown root:root $(binroot)/$(TARGET)"
	sh -c "chmod 311 $(binroot)/$(TARGET)"
	sh -c "rm -f bin/FtpServer-- >/dev/null 2>/dev/null"
	sh -c "mv bin/FtpServer FtpServer-- >/dev/null 2>/dev/null ; $(COPY_FILE) $(TARGET) bin/FtpServer ; chown maa:maa bin/FtpServer ; chmod 6755 bin/FtpServer ; chmod 755 bin/FtpServer"
	sh -c "ls -l bin/FtpServer"
	sh -c "rm -f bin21/FtpServer-- >/dev/null 2>/dev/null"
	sh -c "mv bin21/FtpServer bin21/FtpServer-- >/dev/null 2>/dev/null ; $(COPY_FILE) $(TARGET) bin21/FtpServer ; chown maa:maa bin21/FtpServer ; chmod 755 bin21/FtpServer"
	sh -c "ls -l bin21/FtpServer bin21/FtpServer--"

installr:

uninstall:  

